[package]
name = "aoc22"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
structopt = "0.3.21"
itertools = "0.10.3"
