[package]
name = "aoc21"
version = "0.1.0"
authors = ["Andrew Wright <andrew.wright@metaswitch.com>"]
edition = "2018"
publish = ["metaswitch"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
itertools = "0.10.3"